### ISSUE TITLE
Error in script .\main 64 calibre

### ISSUE THREAD

**Issue by rashuf** [kovidgoyal/build-calibre#16]
Hi!
I run script on build machine after success ending of building dependencies and I get error.

```
C:\scripts>python .\main.py 64 calibre
Installing 46 previously compiled packages: easylzma, zlib, unrar, expat, sqlite
, openssl, python, pywin32, icu, libjpeg, libpng, libwebp, jxrlib, freetype, lib
xml2, libxslt, chmlib, optipng, mozjpeg, poppler, podofo, qt, webkit, sip, pyqt,
 setuptools, six, css-parser, dateutil, dnspython, mechanize, msgpack, regex, ch
ardet, dukpy, unrardll, pygments, pycrypto, apsw, lxml, html5-parser, pillow, ne
tifaces, psutil, webencodings, html5lib,
'C:\sw64\sw\private\python\python.exe' setup.py build '--build-dir=C:\t\t\build-
tqxklb' '--output-dir=C:\t\t\plugins-6lkyhw'

*
* Running build
*


####### Building extension hunspell #######
Compiling hunspell
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    sys.exit(main())
  File "setup.py", line 106, in main
    command.run_all(opts)
  File "C:\calibre\setup\__init__.py", line 242, in run_all
    self.run_cmd(self, opts)
  File "C:\calibre\setup\__init__.py", line 238, in run_cmd
    cmd.run(opts)
  File "C:\calibre\setup\build.py", line 278, in run
    self.build(ext, dest)
  File "C:\calibre\setup\build.py", line 322, in build
    if not parallel_build(jobs, self.info):
  File "C:\calibre\setup\parallel_build.py", line 74, in parallel_build
    for ok, stdout, stderr in p.imap(run_worker, jobs):
  File "C:\sw64\sw\private\python\lib\multiprocessing\pool.py", line 673, in nex
t
    raise value
UnicodeDecodeError: 'utf8' codec can't decode byte 0xaf in position 76: invalid
start byte
The following command failed, with return code: 1
'C:\sw64\sw\private\python\python.exe' setup.py build '--build-dir=C:\t\t\build-
tqxklb' '--output-dir=C:\t\t\plugins-6lkyhw'
Dropping you into a shell
```

**Comment by kovidgoyal** [comment]
Make sure your build machine is using a UTF-8 locale.

**Comment by rashuf** [comment]
Hi Kovid!
Thanks for quick reply!
My OS is Windows 7 SP1 (on VMWare 14). I build calibre by guide. Please, help me. What do i have to do for fixing this error? What settings can I check?

**Comment by kovidgoyal** [comment]
Sorry I'm not a windows user so I cant offer you more detailed help. Basicaly, make sure your windows locale settings are en-US UTF-8 and dont use any non-ascii filenames/directories in the VM.
