### ISSUE TITLE
How do I install calibre-ebook on Linux

### ISSUE THREAD

**Issue by JoeyBling** [kovidgoyal/build-calibre#18]
How do I install calibre-ebook on Linux
an error
```
Using python executable: /usr/bin/python2
2019-06-24 16:27:44 URL:https://download.calibre-ebook.com/linux-installer.sh [31301/31301] -> "-" [1]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 771
    type_map = {x: path for x in 'install_dir isolated bin_dir share_dir ignore_umask'.split()}
                          ^
SyntaxError: invalid syntax
```

**Comment by JoeyBling** [comment]
The documentation on the official website can't help me

**Comment by JoeyBling** [comment]
New problems
```
Failed to find directory to install bash completions, using default.

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________


	Traceback (most recent call last):
	  File "site-packages/calibre/linux.py", line 783, in setup_completion
	  File "site-packages/calibre/linux.py", line 528, in write_completion
	  File "site-packages/calibre/gui2/__init__.py", line 12, in <module>
	ImportError: cannot import name QApplication

Setting up desktop integration...

```

**Comment by lhy6169** [comment]
hi老哥，我遇到了跟你一样的问题，请问下你的问题解决了吗，第一个问题是如何处理的？

**Comment by JoeyBling** [comment]
> hi老哥，我遇到了跟你一样的问题，请问下你的问题解决了吗，第一个问题是如何处理的？

I have solved it.

##### 需要依赖
- python2.7.9 or higher 
- GLIBC_2.17和libstdc++.so

> 官网的说法：- You need GLIBC 2.17 or higher and libstdc++.so.6.0.17 (from gcc 4.7.0) or higher to run calibre

贴上我自己整理的安装文档
[Linux下安装calibre-ebook](https://www.jianshu.com/p/244c2b4632d9)

**Comment by JoeyBling** [comment]
have already solved

#### 贴上我自己整理的安装文档
> #### [Linux下安装calibre-ebook](https://www.jianshu.com/p/244c2b4632d9)
