### ISSUE TITLE
Problem while downloading unrardll

### ISSUE THREAD

**Issue by gberes01** [kovidgoyal/build-calibre#4]
abi@gabi-XPS-13-9350:~/Downloads/build-calibre$ ./linux 64
sudo mkdir -p /home/gabi/Downloads/build-calibre/build/linux/64/container-1/usr/share/terminfo/x
sudo cp -a /lib/terminfo/x/xterm-256color /home/gabi/Downloads/build-calibre/build/linux/64/container-1/usr/share/terminfo/x
sudo chroot --userspec=1000:1000 /home/gabi/Downloads/build-calibre/build/linux/64/container-1 python2 /scripts/main.py

Downloading unrardll-0.1.3.tar.gz from None
Traceback (most recent call last):
  File "/scripts/pkgs/download_sources.py", line 158, in download_pkg
    return try_once(pkg, url)
  File "/scripts/pkgs/download_sources.py", line 149, in try_once
    urllib.urlretrieve(url, fname, reporthook)
  File "/usr/lib/python2.7/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 227, in retrieve
    url = unwrap(toBytes(url))
  File "/usr/lib/python2.7/urllib.py", line 1056, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Download failed, with error: 'NoneType' object has no attribute 'strip'

Downloading unrardll-0.1.3.tar.gz from None
Traceback (most recent call last):
  File "/scripts/pkgs/download_sources.py", line 158, in download_pkg
    return try_once(pkg, url)
  File "/scripts/pkgs/download_sources.py", line 149, in try_once
    urllib.urlretrieve(url, fname, reporthook)
  File "/usr/lib/python2.7/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 227, in retrieve
    url = unwrap(toBytes(url))
  File "/usr/lib/python2.7/urllib.py", line 1056, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Download failed, with error: 'NoneType' object has no attribute 'strip'

Downloading unrardll-0.1.3.tar.gz from None
Traceback (most recent call last):
  File "/scripts/pkgs/download_sources.py", line 158, in download_pkg
    return try_once(pkg, url)
  File "/scripts/pkgs/download_sources.py", line 149, in try_once
    urllib.urlretrieve(url, fname, reporthook)
  File "/usr/lib/python2.7/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 227, in retrieve
    url = unwrap(toBytes(url))
  File "/usr/lib/python2.7/urllib.py", line 1056, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Download failed, with error: 'NoneType' object has no attribute 'strip'

Downloading of unrardll failed after three tries, giving up.

**Comment by kovidgoyal** [comment]
That error indicates you have modified sources.json. THe netry for unrar.ddl should look like:


```json
   {
        "name": "unrardll",
        "unix": {
            "filename": "unrardll-0.1.3.tar.gz",
            "hash": "md5:8830d810f637eefbe829e10488496b6d",
            "urls": ["pypi"]
        }
    },
```

**Comment by gberes01** [comment]
I did not. That's the entry I have in sources.json

**Comment by kovidgoyal** [comment]
In that case, it's likely the pypi page syntax has changed and the code for getting the downlaod URL from pypi needs to be updated.
