### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jiangjiangflies** [kovidgoyal/build-calibre#9]
Hi, kovidgoyal
  I'm trying to build calibre myself but I'm stuck in the first step ( `python setup.py bootstrap`)
I got the following error：
`Already up to date.

*
* Running build
*

Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    sys.exit(main())
  File "setup.py", line 106, in main
    command.run_all(opts)
  File "/root/calibre-3.32.0/setup/__init__.py", line 198, in run_all
    self.run_cmd(self, opts)
  File "/root/calibre-3.32.0/setup/__init__.py", line 190, in run_cmd
    self.run_cmd(scmd, opts)
  File "/root/calibre-3.32.0/setup/__init__.py", line 194, in run_cmd
    cmd.run(opts)
  File "/root/calibre-3.32.0/setup/build.py", line 255, in run
    self.env = init_env()
  File "/root/calibre-3.32.0/setup/build.py", line 150, in init_env
    from setup.build_environment import msvc, is64bit, win_inc, win_lib, NMAKE
  File "/root/calibre-3.32.0/setup/build_environment.py", line 77, in <module>
    qraw = subprocess.check_output([QMAKE, '-query']).decode('utf-8')
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`
I'm using debian 8 to do the builds. What does this OSErros mean?  
Thank you!

**Comment by kovidgoyal** [comment]
you are missing qmake on your PATH.
